version: '3'
services:
 server:
  build: server/
  expose:
  - 3306
  - 1234
  - 1431
  - 1434
  - 1433
  ports:
  - 3306:3306
  - 1234:1234
  - 1431:1431
  - 1433:1433
  - 1434:1434
  container_name: mssql
  environment:
  - MYSQL_ROOT_PASSWORD=Cat_1234
  - MSSQL_SA_PASSWORD=Cat_1234
  - MYSQL_PORT=3306
  - MYSQL_USER=Belka
  - MYSQL_PASSWORD=Cat_1234
  - ACCEPT_EULA="Y"
 client:
  build: client/
  command: python ./client.py
  network_mode: host
  depends_on:
  - server
