#FROM python:latest
#COPY server.py /server/
#COPY index.html /server/
#WORKDIR /server/
#RUN exec pip install BaseHTTPServer
#RUN exec ls -alF
#FROM mcr.microsoft.com/mssql/server
FROM mysql:5.7
#RUN  apt-get update && apt-get install -y openssh-server
#COPY ./server_init.sh /server_init.sh
#RUN exec echo /server_init.sh
#CMD ["./server_init.sh"]
