FROM ubuntu:latest
ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y updaRUN apt-get -y install apache2
#RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
#RUN echo "ServerName localhost" >> /etc/apache2/conf-available/fqdn.conf
RUN apt-get install curl
#WORKDIR var/www/html
RUN curl -O "https://webpagetmp.blob.core.windows.net/web-page/index.html"
RUN curl -O "https://webpagetmp.blob.core.windows.net/web-page/photo.jpg"
RUN cp -f index.html var/www/html/index.html
RUN cp -f photo.jpg var/www/html/photo.jpg

#WORKDIR ~
EXPOSE 80
#CMD ["apachectl", "-D", "FOREGROUND"]
RUN echo "ServerName 10.0.0.4:80" >> /etc/apache2/apache2.conf
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
